from covid_model_seiir_pipeline.pipeline.postprocessing.specification import PostprocessingSpecification
from covid_model_seiir_pipeline.pipeline.postprocessing.data import PostprocessingDataInterface
