"""Static definitions for the compartments and model parameters.

This code is automatically generated by generator/make_constants.py

Any manual changes will be lost.
"""
from collections import (
    namedtuple,
)
import os

import numpy as np
from numba.core import (
    types,
)
from numba.typed import (
    Dict,
)


#######################
# Primitive variables #
#######################

_CompartmentType = namedtuple('CompartmentType', [
    'S', 
    'E', 
    'I', 
    'R', 
    'N', 
])

_TrackingCompartmentType = namedtuple('TrackingCompartmentType', [
    'NewE',         
    'NewR',         
    'NewVaxImmune', 
    'Waned',        
])

_ParameterType = namedtuple('ParameterType', [
    'alpha', 
    'sigma', 
    'gamma', 
    'pi',    
    'new_e', 
    'beta',  
    'kappa', 
    'rho',   
])

_RiskGroup = namedtuple('RiskGroup', [
    'lr', 
    'hr', 
])

_Index1Type = namedtuple('Index1Type', [
    'all',                  
    'total',                
    'ancestral',            
    'alpha',                
    'beta',                 
    'gamma',                
    'delta',                
    'other',                
    'omega',                
    'unprotected',          
    'non_escape_protected', 
    'escape_protected',     
    'omega_protected',      
    'non_escape_immune',    
    'escape_immune',        
    'omega_immune',         
])

_Index2Type = namedtuple('Index2Type', [
    'unvaccinated',     
    'vaccinated',       
    'newly_vaccinated', 
])

_AggIndexType = namedtuple('AggIndexType', [
    'all',                  
    'total',                
    'non_immune',           
    'natural',              
    'vaccine',              
    'vaccine_eligible',     
    'ancestral',            
    'alpha',                
    'beta',                 
    'gamma',                
    'delta',                
    'other',                
    'omega',                
    'unprotected',          
    'non_escape_protected', 
    'escape_protected',     
    'omega_protected',      
    'non_escape_immune',    
    'escape_immune',        
    'omega_immune',         
    'unvaccinated',         
    'vaccinated',           
    'newly_vaccinated',     
])

COMPARTMENT_TYPE = _CompartmentType(*list(range(len(_CompartmentType._fields))))
TRACKING_COMPARTMENT_TYPE = _TrackingCompartmentType(*list(range(len(_TrackingCompartmentType._fields))))
PARAMETER_TYPE = _ParameterType(*list(range(len(_ParameterType._fields))))
RISK_GROUP = _RiskGroup(*list(range(len(_RiskGroup._fields))))
INDEX_1_TYPE = _Index1Type(*list(range(len(_Index1Type._fields))))
INDEX_2_TYPE = _Index2Type(*list(range(len(_Index2Type._fields))))
AGG_INDEX_TYPE = _AggIndexType(*list(range(len(_AggIndexType._fields))))

#####################
# Derived variables #
#####################

_BaseCompartment = namedtuple('BaseCompartment', [
    'S', 
    'E', 
    'I', 
    'R', 
])
BASE_COMPARTMENT = _BaseCompartment(
    S=COMPARTMENT_TYPE.S,
    E=COMPARTMENT_TYPE.E,
    I=COMPARTMENT_TYPE.I,
    R=COMPARTMENT_TYPE.R,
)

_BaseParameter = namedtuple('BaseParameter', [
    'alpha', 
    'sigma', 
    'gamma', 
    'pi',    
    'new_e', 
])
BASE_PARAMETER = _BaseParameter(
    alpha=PARAMETER_TYPE.alpha,
    sigma=PARAMETER_TYPE.sigma,
    gamma=PARAMETER_TYPE.gamma,
    pi=PARAMETER_TYPE.pi,
    new_e=PARAMETER_TYPE.new_e,
)

_VariantParameter = namedtuple('VariantParameter', [
    'beta',  
    'kappa', 
    'rho',   
])
VARIANT_PARAMETER = _VariantParameter(
    beta=PARAMETER_TYPE.beta,
    kappa=PARAMETER_TYPE.kappa,
    rho=PARAMETER_TYPE.rho,
)

_VariantGroup = namedtuple('VariantGroup', [
    'all',   
    'total', 
])
VARIANT_GROUP = _VariantGroup(
    all=INDEX_1_TYPE.all,
    total=INDEX_1_TYPE.total,
)

_Variant = namedtuple('Variant', [
    'ancestral', 
    'alpha',     
    'beta',      
    'gamma',     
    'delta',     
    'other',     
    'omega',     
])
VARIANT = _Variant(
    ancestral=INDEX_1_TYPE.ancestral,
    alpha=INDEX_1_TYPE.alpha,
    beta=INDEX_1_TYPE.beta,
    gamma=INDEX_1_TYPE.gamma,
    delta=INDEX_1_TYPE.delta,
    other=INDEX_1_TYPE.other,
    omega=INDEX_1_TYPE.omega,
)

_SusceptibleType = namedtuple('SusceptibleType', [
    'unprotected',          
    'non_escape_protected', 
    'escape_protected',     
    'omega_protected',      
    'non_escape_immune',    
    'escape_immune',        
    'omega_immune',         
])
SUSCEPTIBLE_TYPE = _SusceptibleType(
    unprotected=INDEX_1_TYPE.unprotected,
    non_escape_protected=INDEX_1_TYPE.non_escape_protected,
    escape_protected=INDEX_1_TYPE.escape_protected,
    omega_protected=INDEX_1_TYPE.omega_protected,
    non_escape_immune=INDEX_1_TYPE.non_escape_immune,
    escape_immune=INDEX_1_TYPE.escape_immune,
    omega_immune=INDEX_1_TYPE.omega_immune,
)

_ProtectionStatus = namedtuple('ProtectionStatus', [
    'unprotected',          
    'non_escape_protected', 
    'escape_protected',     
    'omega_protected',      
])
PROTECTION_STATUS = _ProtectionStatus(
    unprotected=INDEX_1_TYPE.unprotected,
    non_escape_protected=INDEX_1_TYPE.non_escape_protected,
    escape_protected=INDEX_1_TYPE.escape_protected,
    omega_protected=INDEX_1_TYPE.omega_protected,
)

_ImmuneStatus = namedtuple('ImmuneStatus', [
    'non_escape_immune', 
    'escape_immune',     
    'omega_immune',      
])
IMMUNE_STATUS = _ImmuneStatus(
    non_escape_immune=INDEX_1_TYPE.non_escape_immune,
    escape_immune=INDEX_1_TYPE.escape_immune,
    omega_immune=INDEX_1_TYPE.omega_immune,
)

_VaccineType = namedtuple('VaccineType', [
    'unprotected',          
    'non_escape_protected', 
    'escape_protected',     
    'omega_protected',      
    'non_escape_immune',    
    'escape_immune',        
    'omega_immune',         
])
VACCINE_TYPE = _VaccineType(
    unprotected=INDEX_1_TYPE.unprotected,
    non_escape_protected=INDEX_1_TYPE.non_escape_protected,
    escape_protected=INDEX_1_TYPE.escape_protected,
    omega_protected=INDEX_1_TYPE.omega_protected,
    non_escape_immune=INDEX_1_TYPE.non_escape_immune,
    escape_immune=INDEX_1_TYPE.escape_immune,
    omega_immune=INDEX_1_TYPE.omega_immune,
)

_VaccinationStatus = namedtuple('VaccinationStatus', [
    'unvaccinated', 
    'vaccinated',   
])
VACCINATION_STATUS = _VaccinationStatus(
    unvaccinated=INDEX_2_TYPE.unvaccinated,
    vaccinated=INDEX_2_TYPE.vaccinated,
)

_RemovedVaccinationStatus = namedtuple('RemovedVaccinationStatus', [
    'unvaccinated',     
    'vaccinated',       
    'newly_vaccinated', 
])
REMOVED_VACCINATION_STATUS = _RemovedVaccinationStatus(
    unvaccinated=INDEX_2_TYPE.unvaccinated,
    vaccinated=INDEX_2_TYPE.vaccinated,
    newly_vaccinated=INDEX_2_TYPE.newly_vaccinated,
)

_AggVariant = namedtuple('AggVariant', [
    'ancestral', 
    'alpha',     
    'beta',      
    'gamma',     
    'delta',     
    'other',     
    'omega',     
])
AGG_VARIANT = _AggVariant(
    ancestral=AGG_INDEX_TYPE.ancestral,
    alpha=AGG_INDEX_TYPE.alpha,
    beta=AGG_INDEX_TYPE.beta,
    gamma=AGG_INDEX_TYPE.gamma,
    delta=AGG_INDEX_TYPE.delta,
    other=AGG_INDEX_TYPE.other,
    omega=AGG_INDEX_TYPE.omega,
)

_AggImmuneStatus = namedtuple('AggImmuneStatus', [
    'non_escape_immune', 
    'escape_immune',     
    'omega_immune',      
])
AGG_IMMUNE_STATUS = _AggImmuneStatus(
    non_escape_immune=AGG_INDEX_TYPE.non_escape_immune,
    escape_immune=AGG_INDEX_TYPE.escape_immune,
    omega_immune=AGG_INDEX_TYPE.omega_immune,
)

_AggVaccinationStatus = namedtuple('AggVaccinationStatus', [
    'unvaccinated', 
    'vaccinated',   
])
AGG_VACCINATION_STATUS = _AggVaccinationStatus(
    unvaccinated=AGG_INDEX_TYPE.unvaccinated,
    vaccinated=AGG_INDEX_TYPE.vaccinated,
)

_AggOther = namedtuple('AggOther', [
    'all',              
    'total',            
    'non_immune',       
    'unvaccinated',     
    'vaccinated',       
    'vaccine_eligible', 
])
AGG_OTHER = _AggOther(
    all=AGG_INDEX_TYPE.all,
    total=AGG_INDEX_TYPE.total,
    non_immune=AGG_INDEX_TYPE.non_immune,
    unvaccinated=AGG_INDEX_TYPE.unvaccinated,
    vaccinated=AGG_INDEX_TYPE.vaccinated,
    vaccine_eligible=AGG_INDEX_TYPE.vaccine_eligible,
)

PARAMETERS = np.zeros((len(PARAMETER_TYPE), len(INDEX_1_TYPE)), dtype=np.int8)
PARAMETERS[BASE_PARAMETER.alpha, INDEX_1_TYPE.all] = np.int8(0)
PARAMETERS[BASE_PARAMETER.sigma, INDEX_1_TYPE.all] = np.int8(1)
PARAMETERS[BASE_PARAMETER.gamma, INDEX_1_TYPE.all] = np.int8(2)
PARAMETERS[BASE_PARAMETER.pi, INDEX_1_TYPE.all] = np.int8(3)
PARAMETERS[BASE_PARAMETER.new_e, INDEX_1_TYPE.all] = np.int8(4)
PARAMETERS[VARIANT_PARAMETER.beta, VARIANT.ancestral] = np.int8(5)
PARAMETERS[VARIANT_PARAMETER.beta, VARIANT.alpha] = np.int8(6)
PARAMETERS[VARIANT_PARAMETER.beta, VARIANT.beta] = np.int8(7)
PARAMETERS[VARIANT_PARAMETER.beta, VARIANT.gamma] = np.int8(8)
PARAMETERS[VARIANT_PARAMETER.beta, VARIANT.delta] = np.int8(9)
PARAMETERS[VARIANT_PARAMETER.beta, VARIANT.other] = np.int8(10)
PARAMETERS[VARIANT_PARAMETER.beta, VARIANT.omega] = np.int8(11)
PARAMETERS[VARIANT_PARAMETER.kappa, VARIANT.ancestral] = np.int8(12)
PARAMETERS[VARIANT_PARAMETER.kappa, VARIANT.alpha] = np.int8(13)
PARAMETERS[VARIANT_PARAMETER.kappa, VARIANT.beta] = np.int8(14)
PARAMETERS[VARIANT_PARAMETER.kappa, VARIANT.gamma] = np.int8(15)
PARAMETERS[VARIANT_PARAMETER.kappa, VARIANT.delta] = np.int8(16)
PARAMETERS[VARIANT_PARAMETER.kappa, VARIANT.other] = np.int8(17)
PARAMETERS[VARIANT_PARAMETER.kappa, VARIANT.omega] = np.int8(18)
PARAMETERS[VARIANT_PARAMETER.rho, VARIANT.ancestral] = np.int8(19)
PARAMETERS[VARIANT_PARAMETER.rho, VARIANT.alpha] = np.int8(20)
PARAMETERS[VARIANT_PARAMETER.rho, VARIANT.beta] = np.int8(21)
PARAMETERS[VARIANT_PARAMETER.rho, VARIANT.gamma] = np.int8(22)
PARAMETERS[VARIANT_PARAMETER.rho, VARIANT.delta] = np.int8(23)
PARAMETERS[VARIANT_PARAMETER.rho, VARIANT.other] = np.int8(24)
PARAMETERS[VARIANT_PARAMETER.rho, VARIANT.omega] = np.int8(25)
PARAMETERS_NAMES = [
    'alpha_all',
    'sigma_all',
    'gamma_all',
    'pi_all',
    'new_e_all',
    'beta_ancestral',
    'beta_alpha',
    'beta_beta',
    'beta_gamma',
    'beta_delta',
    'beta_other',
    'beta_omega',
    'kappa_ancestral',
    'kappa_alpha',
    'kappa_beta',
    'kappa_gamma',
    'kappa_delta',
    'kappa_other',
    'kappa_omega',
    'rho_ancestral',
    'rho_alpha',
    'rho_beta',
    'rho_gamma',
    'rho_delta',
    'rho_other',
    'rho_omega',
]

VACCINATIONS = np.zeros((len(INDEX_1_TYPE)), dtype=np.int8)
VACCINATIONS[VACCINE_TYPE.unprotected] = np.int8(0)
VACCINATIONS[VACCINE_TYPE.non_escape_protected] = np.int8(1)
VACCINATIONS[VACCINE_TYPE.escape_protected] = np.int8(2)
VACCINATIONS[VACCINE_TYPE.omega_protected] = np.int8(3)
VACCINATIONS[VACCINE_TYPE.non_escape_immune] = np.int8(4)
VACCINATIONS[VACCINE_TYPE.escape_immune] = np.int8(5)
VACCINATIONS[VACCINE_TYPE.omega_immune] = np.int8(6)
VACCINATIONS_NAMES = [
    'unprotected',
    'non_escape_protected',
    'escape_protected',
    'omega_protected',
    'non_escape_immune',
    'escape_immune',
    'omega_immune',
]

COMPARTMENTS = np.zeros((len(COMPARTMENT_TYPE), len(INDEX_1_TYPE), len(INDEX_2_TYPE)), dtype=np.int8)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated] = np.int8(0)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated] = np.int8(1)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated] = np.int8(2)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated] = np.int8(3)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated] = np.int8(4)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated] = np.int8(5)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated] = np.int8(6)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated] = np.int8(7)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated] = np.int8(8)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated] = np.int8(9)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated] = np.int8(10)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.vaccinated] = np.int8(11)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.unvaccinated] = np.int8(12)
COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.vaccinated] = np.int8(13)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated] = np.int8(14)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.vaccinated] = np.int8(15)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.unvaccinated] = np.int8(16)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.vaccinated] = np.int8(17)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.unvaccinated] = np.int8(18)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.vaccinated] = np.int8(19)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.unvaccinated] = np.int8(20)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.vaccinated] = np.int8(21)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.unvaccinated] = np.int8(22)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.vaccinated] = np.int8(23)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.unvaccinated] = np.int8(24)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.vaccinated] = np.int8(25)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.unvaccinated] = np.int8(26)
COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.vaccinated] = np.int8(27)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated] = np.int8(28)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.vaccinated] = np.int8(29)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.unvaccinated] = np.int8(30)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.vaccinated] = np.int8(31)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.unvaccinated] = np.int8(32)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.vaccinated] = np.int8(33)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.unvaccinated] = np.int8(34)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.vaccinated] = np.int8(35)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.unvaccinated] = np.int8(36)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.vaccinated] = np.int8(37)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.unvaccinated] = np.int8(38)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.vaccinated] = np.int8(39)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.unvaccinated] = np.int8(40)
COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.vaccinated] = np.int8(41)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated] = np.int8(42)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated] = np.int8(43)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.newly_vaccinated] = np.int8(44)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated] = np.int8(45)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated] = np.int8(46)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.newly_vaccinated] = np.int8(47)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated] = np.int8(48)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated] = np.int8(49)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.newly_vaccinated] = np.int8(50)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated] = np.int8(51)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated] = np.int8(52)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.newly_vaccinated] = np.int8(53)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated] = np.int8(54)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated] = np.int8(55)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.newly_vaccinated] = np.int8(56)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated] = np.int8(57)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated] = np.int8(58)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.newly_vaccinated] = np.int8(59)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated] = np.int8(60)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated] = np.int8(61)
COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.newly_vaccinated] = np.int8(62)
COMPARTMENTS_NAMES = [
    'S_unprotected_unvaccinated',
    'S_unprotected_vaccinated',
    'S_non_escape_protected_unvaccinated',
    'S_non_escape_protected_vaccinated',
    'S_escape_protected_unvaccinated',
    'S_escape_protected_vaccinated',
    'S_omega_protected_unvaccinated',
    'S_omega_protected_vaccinated',
    'S_non_escape_immune_unvaccinated',
    'S_non_escape_immune_vaccinated',
    'S_escape_immune_unvaccinated',
    'S_escape_immune_vaccinated',
    'S_omega_immune_unvaccinated',
    'S_omega_immune_vaccinated',
    'E_ancestral_unvaccinated',
    'E_ancestral_vaccinated',
    'E_alpha_unvaccinated',
    'E_alpha_vaccinated',
    'E_beta_unvaccinated',
    'E_beta_vaccinated',
    'E_gamma_unvaccinated',
    'E_gamma_vaccinated',
    'E_delta_unvaccinated',
    'E_delta_vaccinated',
    'E_other_unvaccinated',
    'E_other_vaccinated',
    'E_omega_unvaccinated',
    'E_omega_vaccinated',
    'I_ancestral_unvaccinated',
    'I_ancestral_vaccinated',
    'I_alpha_unvaccinated',
    'I_alpha_vaccinated',
    'I_beta_unvaccinated',
    'I_beta_vaccinated',
    'I_gamma_unvaccinated',
    'I_gamma_vaccinated',
    'I_delta_unvaccinated',
    'I_delta_vaccinated',
    'I_other_unvaccinated',
    'I_other_vaccinated',
    'I_omega_unvaccinated',
    'I_omega_vaccinated',
    'R_ancestral_unvaccinated',
    'R_ancestral_vaccinated',
    'R_ancestral_newly_vaccinated',
    'R_alpha_unvaccinated',
    'R_alpha_vaccinated',
    'R_alpha_newly_vaccinated',
    'R_beta_unvaccinated',
    'R_beta_vaccinated',
    'R_beta_newly_vaccinated',
    'R_gamma_unvaccinated',
    'R_gamma_vaccinated',
    'R_gamma_newly_vaccinated',
    'R_delta_unvaccinated',
    'R_delta_vaccinated',
    'R_delta_newly_vaccinated',
    'R_other_unvaccinated',
    'R_other_vaccinated',
    'R_other_newly_vaccinated',
    'R_omega_unvaccinated',
    'R_omega_vaccinated',
    'R_omega_newly_vaccinated',
]

TRACKING_COMPARTMENTS = np.zeros((len(TRACKING_COMPARTMENT_TYPE), len(AGG_INDEX_TYPE)), dtype=np.int8)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VACCINATION_STATUS.unvaccinated] = np.int8(63)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VACCINATION_STATUS.vaccinated] = np.int8(64)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VARIANT.ancestral] = np.int8(65)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VARIANT.alpha] = np.int8(66)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VARIANT.beta] = np.int8(67)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VARIANT.gamma] = np.int8(68)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VARIANT.delta] = np.int8(69)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VARIANT.other] = np.int8(70)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_VARIANT.omega] = np.int8(71)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewE, AGG_INDEX_TYPE.total] = np.int8(72)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewVaxImmune, AGG_IMMUNE_STATUS.non_escape_immune] = np.int8(73)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewVaxImmune, AGG_IMMUNE_STATUS.escape_immune] = np.int8(74)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewVaxImmune, AGG_IMMUNE_STATUS.omega_immune] = np.int8(75)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewVaxImmune, AGG_INDEX_TYPE.total] = np.int8(76)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewR, AGG_VARIANT.ancestral] = np.int8(77)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewR, AGG_VARIANT.alpha] = np.int8(78)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewR, AGG_VARIANT.beta] = np.int8(79)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewR, AGG_VARIANT.gamma] = np.int8(80)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewR, AGG_VARIANT.delta] = np.int8(81)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewR, AGG_VARIANT.other] = np.int8(82)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewR, AGG_VARIANT.omega] = np.int8(83)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.NewR, AGG_INDEX_TYPE.total] = np.int8(84)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_INDEX_TYPE.natural] = np.int8(85)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_INDEX_TYPE.vaccine] = np.int8(86)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_VARIANT.ancestral] = np.int8(87)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_VARIANT.alpha] = np.int8(88)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_VARIANT.beta] = np.int8(89)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_VARIANT.gamma] = np.int8(90)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_VARIANT.delta] = np.int8(91)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_VARIANT.other] = np.int8(92)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_VARIANT.omega] = np.int8(93)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_IMMUNE_STATUS.non_escape_immune] = np.int8(94)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_IMMUNE_STATUS.escape_immune] = np.int8(95)
TRACKING_COMPARTMENTS[TRACKING_COMPARTMENT_TYPE.Waned, AGG_IMMUNE_STATUS.omega_immune] = np.int8(96)
TRACKING_COMPARTMENTS_NAMES = [
    'NewE_unvaccinated',
    'NewE_vaccinated',
    'NewE_ancestral',
    'NewE_alpha',
    'NewE_beta',
    'NewE_gamma',
    'NewE_delta',
    'NewE_other',
    'NewE_omega',
    'NewE_total',
    'NewVaxImmune_non_escape_immune',
    'NewVaxImmune_escape_immune',
    'NewVaxImmune_omega_immune',
    'NewVaxImmune_total',
    'NewR_ancestral',
    'NewR_alpha',
    'NewR_beta',
    'NewR_gamma',
    'NewR_delta',
    'NewR_other',
    'NewR_omega',
    'NewR_total',
    'Waned_natural',
    'Waned_vaccine',
    'Waned_ancestral',
    'Waned_alpha',
    'Waned_beta',
    'Waned_gamma',
    'Waned_delta',
    'Waned_other',
    'Waned_omega',
    'Waned_non_escape_immune',
    'Waned_escape_immune',
    'Waned_omega_immune',
]

AGGREGATES = np.zeros((len(COMPARTMENT_TYPE), len(AGG_INDEX_TYPE)), dtype=np.int8)
AGGREGATES[BASE_COMPARTMENT.S, AGG_VARIANT.ancestral] = np.int8(0)
AGGREGATES[BASE_COMPARTMENT.S, AGG_VARIANT.alpha] = np.int8(1)
AGGREGATES[BASE_COMPARTMENT.S, AGG_VARIANT.beta] = np.int8(2)
AGGREGATES[BASE_COMPARTMENT.S, AGG_VARIANT.gamma] = np.int8(3)
AGGREGATES[BASE_COMPARTMENT.S, AGG_VARIANT.delta] = np.int8(4)
AGGREGATES[BASE_COMPARTMENT.S, AGG_VARIANT.other] = np.int8(5)
AGGREGATES[BASE_COMPARTMENT.S, AGG_VARIANT.omega] = np.int8(6)
AGGREGATES[BASE_COMPARTMENT.E, AGG_VARIANT.ancestral] = np.int8(7)
AGGREGATES[BASE_COMPARTMENT.E, AGG_VARIANT.alpha] = np.int8(8)
AGGREGATES[BASE_COMPARTMENT.E, AGG_VARIANT.beta] = np.int8(9)
AGGREGATES[BASE_COMPARTMENT.E, AGG_VARIANT.gamma] = np.int8(10)
AGGREGATES[BASE_COMPARTMENT.E, AGG_VARIANT.delta] = np.int8(11)
AGGREGATES[BASE_COMPARTMENT.E, AGG_VARIANT.other] = np.int8(12)
AGGREGATES[BASE_COMPARTMENT.E, AGG_VARIANT.omega] = np.int8(13)
AGGREGATES[BASE_COMPARTMENT.I, AGG_VARIANT.ancestral] = np.int8(14)
AGGREGATES[BASE_COMPARTMENT.I, AGG_VARIANT.alpha] = np.int8(15)
AGGREGATES[BASE_COMPARTMENT.I, AGG_VARIANT.beta] = np.int8(16)
AGGREGATES[BASE_COMPARTMENT.I, AGG_VARIANT.gamma] = np.int8(17)
AGGREGATES[BASE_COMPARTMENT.I, AGG_VARIANT.delta] = np.int8(18)
AGGREGATES[BASE_COMPARTMENT.I, AGG_VARIANT.other] = np.int8(19)
AGGREGATES[BASE_COMPARTMENT.I, AGG_VARIANT.omega] = np.int8(20)
AGGREGATES[BASE_COMPARTMENT.R, AGG_VARIANT.ancestral] = np.int8(21)
AGGREGATES[BASE_COMPARTMENT.R, AGG_VARIANT.alpha] = np.int8(22)
AGGREGATES[BASE_COMPARTMENT.R, AGG_VARIANT.beta] = np.int8(23)
AGGREGATES[BASE_COMPARTMENT.R, AGG_VARIANT.gamma] = np.int8(24)
AGGREGATES[BASE_COMPARTMENT.R, AGG_VARIANT.delta] = np.int8(25)
AGGREGATES[BASE_COMPARTMENT.R, AGG_VARIANT.other] = np.int8(26)
AGGREGATES[BASE_COMPARTMENT.R, AGG_VARIANT.omega] = np.int8(27)
AGGREGATES[COMPARTMENT_TYPE.N, AGG_VACCINATION_STATUS.unvaccinated] = np.int8(28)
AGGREGATES[COMPARTMENT_TYPE.N, AGG_VACCINATION_STATUS.vaccinated] = np.int8(29)
AGGREGATES_NAMES = [
    'S_ancestral',
    'S_alpha',
    'S_beta',
    'S_gamma',
    'S_delta',
    'S_other',
    'S_omega',
    'E_ancestral',
    'E_alpha',
    'E_beta',
    'E_gamma',
    'E_delta',
    'E_other',
    'E_omega',
    'I_ancestral',
    'I_alpha',
    'I_beta',
    'I_gamma',
    'I_delta',
    'I_other',
    'I_omega',
    'R_ancestral',
    'R_alpha',
    'R_beta',
    'R_gamma',
    'R_delta',
    'R_other',
    'R_omega',
    'N_unvaccinated',
    'N_vaccinated',
]

FORCE_OF_INFECTION = np.zeros((len(INDEX_1_TYPE)), dtype=np.int8)
FORCE_OF_INFECTION[VARIANT.ancestral] = np.int8(0)
FORCE_OF_INFECTION[VARIANT.alpha] = np.int8(1)
FORCE_OF_INFECTION[VARIANT.beta] = np.int8(2)
FORCE_OF_INFECTION[VARIANT.gamma] = np.int8(3)
FORCE_OF_INFECTION[VARIANT.delta] = np.int8(4)
FORCE_OF_INFECTION[VARIANT.other] = np.int8(5)
FORCE_OF_INFECTION[VARIANT.omega] = np.int8(6)
FORCE_OF_INFECTION_NAMES = [
    'ancestral',
    'alpha',
    'beta',
    'gamma',
    'delta',
    'other',
    'omega',
]

WANED = np.zeros((len(AGG_INDEX_TYPE)), dtype=np.int8)
WANED[AGG_INDEX_TYPE.natural] = np.int8(0)
WANED[AGG_INDEX_TYPE.vaccine] = np.int8(1)
WANED_NAMES = [
    'natural',
    'vaccine',
]

CG_SUSCEPTIBLE = Dict.empty(
    types.int8,
    types.int8[:],
)
CG_SUSCEPTIBLE[AGG_VARIANT.ancestral] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_SUSCEPTIBLE[AGG_VARIANT.alpha] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_SUSCEPTIBLE[AGG_VARIANT.beta] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_SUSCEPTIBLE[AGG_VARIANT.gamma] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_SUSCEPTIBLE[AGG_VARIANT.delta] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_SUSCEPTIBLE[AGG_VARIANT.other] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_SUSCEPTIBLE[AGG_VARIANT.omega] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_SUSCEPTIBLE[AGG_OTHER.non_immune] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_SUSCEPTIBLE[AGG_OTHER.total] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_EXPOSED = Dict.empty(
    types.int8,
    types.int8[:],
)
CG_EXPOSED[AGG_VARIANT.ancestral] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_EXPOSED[AGG_VARIANT.alpha] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_EXPOSED[AGG_VARIANT.beta] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_EXPOSED[AGG_VARIANT.gamma] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_EXPOSED[AGG_VARIANT.delta] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_EXPOSED[AGG_VARIANT.other] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_EXPOSED[AGG_VARIANT.omega] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_EXPOSED[AGG_OTHER.total] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_INFECTIOUS = Dict.empty(
    types.int8,
    types.int8[:],
)
CG_INFECTIOUS[AGG_VARIANT.ancestral] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_INFECTIOUS[AGG_VARIANT.alpha] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_INFECTIOUS[AGG_VARIANT.beta] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_INFECTIOUS[AGG_VARIANT.gamma] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_INFECTIOUS[AGG_VARIANT.delta] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_INFECTIOUS[AGG_VARIANT.other] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_INFECTIOUS[AGG_VARIANT.omega] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_INFECTIOUS[AGG_OTHER.total] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
], dtype=np.int8)
CG_REMOVED = Dict.empty(
    types.int8,
    types.int8[:],
)
CG_REMOVED[AGG_VARIANT.ancestral] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_REMOVED[AGG_VARIANT.alpha] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_REMOVED[AGG_VARIANT.beta] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_REMOVED[AGG_VARIANT.gamma] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_REMOVED[AGG_VARIANT.delta] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_REMOVED[AGG_VARIANT.other] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_REMOVED[AGG_VARIANT.omega] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_REMOVED[AGG_OTHER.total] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.ancestral, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.alpha, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.beta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.gamma, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.delta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.other, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, AGG_VARIANT.omega, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_TOTAL = Dict.empty(
    types.int8,
    types.int8[:],
)
CG_TOTAL[AGG_OTHER.total] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_TOTAL[AGG_OTHER.unvaccinated] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_TOTAL[AGG_OTHER.vaccinated] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)
CG_TOTAL[AGG_OTHER.vaccine_eligible] = np.array([
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.unprotected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_protected, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.non_escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.escape_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.S, SUSCEPTIBLE_TYPE.omega_immune, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.E, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.ancestral, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.alpha, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.beta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.gamma, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.delta, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.other, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.I, VARIANT.omega, VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.ancestral, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.alpha, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.beta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.gamma, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.delta, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.other, REMOVED_VACCINATION_STATUS.newly_vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.unvaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.vaccinated],
    COMPARTMENTS[COMPARTMENT_TYPE.R, VARIANT.omega, REMOVED_VACCINATION_STATUS.newly_vaccinated],
], dtype=np.int8)

# Turning off the JIT is operationally 1-to-1 with
# saying something is broken in the ODE code and
# I need to figure it out.
DEBUG = int(os.getenv('NUMBA_DISABLE_JIT', 0))
