"""Static definitions for data containers.

This code is automatically generated by generator/make_containers.py

Any manual changes will be lost.
"""
from dataclasses import (
    dataclass,
)
from typing import (
    Dict,
    List,
    Iterator,
    Tuple,
)

import pandas as pd

from covid_model_seiir_pipeline.lib import (
    utilities,
)


@dataclass(repr=False, eq=False)
class Parameters:
    alpha: pd.Series
    sigma: pd.Series
    gamma: pd.Series
    pi: pd.Series
    new_e: pd.Series
    beta_ancestral: pd.Series
    beta_alpha: pd.Series
    beta_beta: pd.Series
    beta_gamma: pd.Series
    beta_delta: pd.Series
    beta_omega: pd.Series
    kappa_ancestral: pd.Series
    kappa_alpha: pd.Series
    kappa_beta: pd.Series
    kappa_gamma: pd.Series
    kappa_delta: pd.Series
    kappa_omega: pd.Series
    rho_ancestral: pd.Series
    rho_alpha: pd.Series
    rho_beta: pd.Series
    rho_gamma: pd.Series
    rho_delta: pd.Series
    rho_omega: pd.Series

    vaccinations_unprotected_lr: pd.Series
    vaccinations_unprotected_hr: pd.Series
    vaccinations_non_escape_protected_lr: pd.Series
    vaccinations_non_escape_protected_hr: pd.Series
    vaccinations_escape_protected_lr: pd.Series
    vaccinations_escape_protected_hr: pd.Series
    vaccinations_omega_protected_lr: pd.Series
    vaccinations_omega_protected_hr: pd.Series
    vaccinations_non_escape_immune_lr: pd.Series
    vaccinations_non_escape_immune_hr: pd.Series
    vaccinations_escape_immune_lr: pd.Series
    vaccinations_escape_immune_hr: pd.Series
    vaccinations_omega_immune_lr: pd.Series
    vaccinations_omega_immune_hr: pd.Series

    def to_dict(self) -> Dict[str, pd.Series]:
        return {k: v.rename(k) for k, v in utilities.asdict(self).items()}

    def to_df(self) -> pd.DataFrame:
        return pd.concat(self.to_dict().values(), axis=1)

    def reindex(self, index: pd.Index) -> 'Parameters':
        # noinspection PyArgumentList
        return type(self)(
            **{key: value.reindex(index) for key, value in self.to_dict().items()}
        )
    